#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

#include <GLFW/glfw3.h>

#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif

#include "renderer.h"
#include "sim_cpu.h"
#include "types.h"

#ifdef USE_CUDA
#include "simulation.h"
#endif

static constexpr int CHAMBER_NODE = -1;

// =============================================================================
// main.cpp — Application entry point and runtime controller
//
// Provides:
//   1. Command-line parsing for CPU, CUDA, replay, visual, and headless modes
//   2. Protocol setup for load, concentrate, wash, harvest, and full protocol runs
//   3. Visual OpenGL simulation loop
//   4. Headless benchmark loop for update-only timing
//   5. Benchmark summary reporting for CPU/CUDA/replay comparisons
//
// Notes:
//   - Visual mode measures the full synchronous application loop:
//       system update + particle update + render/swap/poll.
//   - Headless mode skips OpenGL and isolates update-loop performance.
//   - Replay mode visualizes particle frames generated by the CUDA frame generator.
// =============================================================================

enum class RunMode {
    Cpu,
    Cuda,
    Replay
};

enum class StepSelection {
    Protocol,
    Load,
    Concentrate,
    Wash,
    Harvest
};

struct AppConfig {
    RunMode mode = RunMode::Cpu;
    int totalParticles = 5000;
    float durationSeconds = -1.0f;
    int benchmarkSteps = 0;
    bool headless = false;
    std::string replayPath;
    StepSelection stepSelection = StepSelection::Protocol;
};

struct GeometryConfig {
    float chamberHeight = 2.5f;

    // y = -height/2 is the narrow inlet/tip.
    // y = +height/2 is the wider upper chamber.
    float outerBase = 0.28f;
    float outerTip  = 1.15f;

    float innerBase = 0.12f;
    float innerTip  = 0.55f;
};

struct BenchmarkStats {
    int frames = 0;
    double totalRuntimeMs = 0.0;
    double fullFrameMs = 0.0;
    double particleUpdateMs = 0.0;
    double systemUpdateMs = 0.0;
    double renderMs = 0.0;
};

struct ReplayHeader {
    char magic[8];
    std::uint32_t version;
    std::uint32_t particleCount;
    std::uint32_t frameCount;
    float dt;
};

struct ReplayData {
    int particleCount = 0;
    int frameCount = 0;
    float dt = 0.016f;
    std::vector<Particle> frames;
};

static void glfw_error_callback(int error, const char* description) {
    std::cerr << "GLFW Error [" << error << "]: "
              << (description ? description : "unknown") << std::endl;
}

static double nowSeconds() {
    using clock = std::chrono::high_resolution_clock;
    static const auto start = clock::now();
    const auto current = clock::now();
    return std::chrono::duration<double>(current - start).count();
}

static double secondsToMs(double seconds) {
    return seconds * 1000.0;
}

static const char* modeName(RunMode mode) {
    switch (mode) {
        case RunMode::Cpu:
            return "cpu";
        case RunMode::Cuda:
            return "cuda";
        case RunMode::Replay:
            return "replay";
        default:
            return "unknown";
    }
}

static const char* stepName(StepSelection step) {
    switch (step) {
        case StepSelection::Protocol:
            return "protocol";
        case StepSelection::Load:
            return "load";
        case StepSelection::Concentrate:
            return "concentrate";
        case StepSelection::Wash:
            return "wash";
        case StepSelection::Harvest:
            return "harvest";
        default:
            return "unknown";
    }
}

static int phaseToInt(PhaseType phase) {
    switch (phase) {
        case PhaseType::Load:
            return 0;
        case PhaseType::Concentrate:
            return 1;
        case PhaseType::Wash:
            return 2;
        case PhaseType::Harvest:
            return 3;
        default:
            return 0;
    }
}

static void printUsage(const char* programName) {
    std::cout
        << "Usage: " << programName << " [options]\n\n"
        << "Options:\n"
        << "  --mode cpu             Live CPU simulation. Default.\n"
#ifdef USE_CUDA
        << "  --mode cuda            Live CUDA particle simulation.\n"
#endif
        << "  --mode replay          Replay CUDA-generated particle frames.\n"
        << "  --replay PATH          Path to replay frame file.\n"
        << "  --particles N          Total particles for live simulation. Default: 5000\n"
        << "  --duration S           Run for S seconds, then exit. Default: indefinite\n"
        << "  --headless             Run update benchmark without OpenGL rendering.\n"
        << "  --steps N              Number of update steps for headless benchmark.\n"
        << "  --step protocol        Cycle Load -> Concentrate -> Wash -> Harvest. Default.\n"
        << "  --step load            Run only the Load step.\n"
        << "  --step concentrate     Run only the Concentrate step.\n"
        << "  --step wash            Run only the Wash step.\n"
        << "  --step harvest         Run only the Harvest step.\n"
        << "  --help                 Show this help message\n\n"
        << "Examples:\n"
        << "  " << programName << " --mode cpu --step protocol --particles 5000 --duration 30\n"
#ifdef USE_CUDA
        << "  " << programName << " --mode cuda --step wash --particles 5000 --duration 30\n"
#endif
        << "  " << programName << " --mode cpu --headless --particles 100000 --steps 10000\n"
#ifdef USE_CUDA
        << "  " << programName << " --mode cuda --headless --particles 100000 --steps 10000\n"
#endif
        << "  " << programName << " --mode replay --replay frames.bin --duration 30\n";
}

static bool parseIntArg(const char* value, int& out) {
    if (value == nullptr) {
        return false;
    }

    char* end = nullptr;
    long parsed = std::strtol(value, &end, 10);

    if (end == value || *end != '\0' || parsed <= 0 ||
        parsed > std::numeric_limits<int>::max()) {
        return false;
    }

    out = static_cast<int>(parsed);
    return true;
}

static bool parseFloatArg(const char* value, float& out) {
    if (value == nullptr) {
        return false;
    }

    char* end = nullptr;
    float parsed = std::strtof(value, &end);

    if (end == value || *end != '\0' || parsed <= 0.0f ||
        !std::isfinite(parsed)) {
        return false;
    }

    out = parsed;
    return true;
}

static bool parseModeArg(const std::string& value, RunMode& out) {
    if (value == "cpu") {
        out = RunMode::Cpu;
        return true;
    }

#ifdef USE_CUDA
    if (value == "cuda") {
        out = RunMode::Cuda;
        return true;
    }
#else
    if (value == "cuda") {
        std::cerr
            << "This binary was built without CUDA support. "
            << "Use --mode cpu/replay or rebuild with USE_CUDA.\n";
        return false;
    }
#endif

    if (value == "replay") {
        out = RunMode::Replay;
        return true;
    }

    return false;
}

static bool parseStepArg(const std::string& value, StepSelection& out) {
    if (value == "protocol") {
        out = StepSelection::Protocol;
        return true;
    }

    if (value == "load") {
        out = StepSelection::Load;
        return true;
    }

    if (value == "concentrate") {
        out = StepSelection::Concentrate;
        return true;
    }

    if (value == "wash") {
        out = StepSelection::Wash;
        return true;
    }

    if (value == "harvest") {
        out = StepSelection::Harvest;
        return true;
    }

    return false;
}

static bool parseArgs(int argc, char** argv, AppConfig& config) {
    for (int i = 1; i < argc; ++i) {
        if (argv[i] == nullptr) {
            continue;
        }

        std::string arg = argv[i];

        if (arg == "--help" || arg == "-h") {
            printUsage(argv[0]);
            return false;
        }

        if (arg == "--mode") {
            if (i + 1 >= argc || !parseModeArg(argv[++i], config.mode)) {
#ifdef USE_CUDA
                std::cerr << "Invalid value for --mode. Use cpu, cuda, or replay.\n";
#else
                std::cerr << "Invalid value for --mode. Use cpu or replay.\n";
#endif
                return false;
            }
            continue;
        }

        if (arg == "--step") {
            if (i + 1 >= argc || !parseStepArg(argv[++i], config.stepSelection)) {
                std::cerr
                    << "Invalid value for --step. Use protocol, load, concentrate, wash, or harvest.\n";
                return false;
            }
            continue;
        }

        if (arg == "--particles") {
            if (i + 1 >= argc ||
                !parseIntArg(argv[++i], config.totalParticles)) {
                std::cerr << "Invalid value for --particles. Use a positive integer.\n";
                return false;
            }
            continue;
        }

        if (arg == "--duration") {
            if (i + 1 >= argc ||
                !parseFloatArg(argv[++i], config.durationSeconds)) {
                std::cerr << "Invalid value for --duration. Use a positive number.\n";
                return false;
            }
            continue;
        }

        if (arg == "--steps") {
            if (i + 1 >= argc ||
                !parseIntArg(argv[++i], config.benchmarkSteps)) {
                std::cerr << "Invalid value for --steps. Use a positive integer.\n";
                return false;
            }
            continue;
        }

        if (arg == "--headless") {
            config.headless = true;
            continue;
        }

        if (arg == "--replay") {
            if (i + 1 >= argc || argv[i + 1] == nullptr) {
                std::cerr << "Missing path after --replay.\n";
                return false;
            }

            config.replayPath = argv[++i];
            continue;
        }

        std::cerr << "Unknown argument: " << arg << "\n";
        printUsage(argv[0]);
        return false;
    }

    if (config.mode == RunMode::Replay && config.replayPath.empty()) {
        std::cerr << "Replay mode requires --replay PATH.\n";
        return false;
    }

    if (config.headless && config.mode == RunMode::Replay) {
        std::cerr << "Headless mode supports cpu or cuda, not replay.\n";
        return false;
    }

    if (config.headless && config.benchmarkSteps <= 0) {
        if (config.durationSeconds > 0.0f) {
            config.benchmarkSteps =
                std::max(1, static_cast<int>(config.durationSeconds / 0.016f));
        } else {
            config.benchmarkSteps = 10000;
        }
    }

    if (config.mode == RunMode::Replay &&
        config.stepSelection != StepSelection::Protocol) {
        std::cerr
            << "Note: --step is ignored in replay mode because replay frames are precomputed.\n";
    }

    return true;
}

static bool validateReplayHeader(const ReplayHeader& header) {
    const char expectedMagic[8] = {'R', 'O', 'T', 'E', 'A', 'F', 'R', 'M'};

    if (std::memcmp(header.magic, expectedMagic, 8) != 0) {
        std::cerr << "Invalid replay file magic.\n";
        return false;
    }

    if (header.version != 1) {
        std::cerr << "Unsupported replay file version: "
                  << header.version << "\n";
        return false;
    }

    if (header.particleCount == 0 || header.frameCount == 0) {
        std::cerr << "Replay file has invalid particle/frame count.\n";
        return false;
    }

    if (!std::isfinite(header.dt) || header.dt <= 0.0f) {
        std::cerr << "Replay file has invalid dt.\n";
        return false;
    }

    return true;
}

static bool loadReplayFile(const std::string& path, ReplayData& replay) {
    std::ifstream in(path, std::ios::binary);

    if (!in) {
        std::cerr << "Failed to open replay file: " << path << "\n";
        return false;
    }

    ReplayHeader header{};
    in.read(reinterpret_cast<char*>(&header), sizeof(header));

    if (!in || !validateReplayHeader(header)) {
        std::cerr << "Failed to read valid replay header.\n";
        return false;
    }

    const std::size_t particleCount =
        static_cast<std::size_t>(header.particleCount);
    const std::size_t frameCount =
        static_cast<std::size_t>(header.frameCount);

    if (particleCount > std::numeric_limits<std::size_t>::max() / frameCount) {
        std::cerr << "Replay particle/frame count overflow.\n";
        return false;
    }

    const std::size_t totalParticles = particleCount * frameCount;

    if (totalParticles >
        std::numeric_limits<std::size_t>::max() / sizeof(Particle)) {
        std::cerr << "Replay byte count overflow.\n";
        return false;
    }

    const std::size_t totalBytes = totalParticles * sizeof(Particle);
    const std::size_t maxReplayBytes =
        static_cast<std::size_t>(2ULL * 1024ULL * 1024ULL * 1024ULL);

    if (totalBytes > maxReplayBytes) {
        std::cerr
            << "Replay file too large to load safely: "
            << totalBytes
            << " bytes. Generate fewer frames while debugging.\n";
        return false;
    }

    replay.particleCount = static_cast<int>(header.particleCount);
    replay.frameCount = static_cast<int>(header.frameCount);
    replay.dt = header.dt;

    replay.frames.resize(totalParticles);

    in.read(
        reinterpret_cast<char*>(replay.frames.data()),
        static_cast<std::streamsize>(totalBytes)
    );

    if (!in) {
        std::cerr << "Replay file ended before all particle frames were read.\n";
        return false;
    }

    std::cout
        << "Loaded replay file: " << path << "\n"
        << "Replay particles: " << replay.particleCount << "\n"
        << "Replay frames: " << replay.frameCount << "\n"
        << "Replay dt: " << replay.dt << "\n";

    return true;
}

static GLFWwindow* createWindow(const AppConfig& config) {
    glfwSetErrorCallback(glfw_error_callback);

    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW.\n";
        return nullptr;
    }

    std::string title;

    if (config.mode == RunMode::Cpu) {
        title = "Rotea CPU/OpenGL Particle Simulation";
    } else if (config.mode == RunMode::Cuda) {
        title = "Rotea CUDA/OpenGL Particle Simulation";
    } else {
        title = "Rotea CUDA Frame Replay Visualization";
    }

    GLFWwindow* window = glfwCreateWindow(
        1200,
        800,
        title.c_str(),
        nullptr,
        nullptr
    );

    if (!window) {
        std::cerr << "Failed to create GLFW window.\n";
        glfwTerminate();
        return nullptr;
    }

    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    return window;
}

static Step makeStepForSelection(StepSelection selection) {
    switch (selection) {
        case StepSelection::Load:
            return {
                "Load",
                PhaseType::Load,
                999999.0f,
                1200.0f,
                {20.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}
            };

        case StepSelection::Concentrate:
            return {
                "Concentrate",
                PhaseType::Concentrate,
                999999.0f,
                3000.0f,
                {0.0f, 12.0f, 0.0f, 6.0f, 0.0f, 0.0f, 0.0f, 0.0f}
            };

        case StepSelection::Wash:
            return {
                "Wash",
                PhaseType::Wash,
                999999.0f,
                2600.0f,
                {0.0f, 15.0f, 0.0f, 8.0f, 0.0f, 0.0f, 0.0f, 0.0f}
            };

        case StepSelection::Harvest:
            return {
                "Harvest",
                PhaseType::Harvest,
                999999.0f,
                800.0f,
                {0.0f, 0.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}
            };

        case StepSelection::Protocol:
        default:
            return {
                "Load",
                PhaseType::Load,
                8.0f,
                1200.0f,
                {20.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}
            };
    }
}

// Initializes the simplified Rotea-inspired protocol state.
// In protocol mode, the app cycles through load, concentrate, wash, and harvest.
// In single-step mode, one long-running phase is used for focused benchmarking.
static void initCpuProtocol(
    std::vector<Bag>& bags,
    Chamber& chamber,
    std::vector<Line>& lines,
    std::vector<Step>& protocol,
    StepSelection stepSelection
) {
    bags = {
        {"Sample",  500.0f, 0.0f},
        {"Buffer",  500.0f, 0.0f},
        {"Product",   0.0f, 0.0f},
        {"Waste",     0.0f, 0.0f}
    };

    chamber = {
        0.0f,
        0.0f,
        1.00f,
        1.00f,
        0.0f
    };

    lines.resize(8);
    lines[0] = {LineID::A, 0,            CHAMBER_NODE, 0.0f, true};
    lines[1] = {LineID::B, 1,            CHAMBER_NODE, 0.0f, true};
    lines[2] = {LineID::C, CHAMBER_NODE, 2,            0.0f, true};
    lines[3] = {LineID::D, CHAMBER_NODE, 3,            0.0f, true};
    lines[4] = {LineID::E, CHAMBER_NODE, 2,            0.0f, true};
    lines[5] = {LineID::F, CHAMBER_NODE, 3,            0.0f, true};
    lines[6] = {LineID::G, 2,            CHAMBER_NODE, 0.0f, true};
    lines[7] = {LineID::H, CHAMBER_NODE, 2,            0.0f, true};

    if (stepSelection != StepSelection::Protocol) {
        protocol = { makeStepForSelection(stepSelection) };
        return;
    }

    protocol = {
        {
            "Load",
            PhaseType::Load,
            8.0f,
            1200.0f,
            {20.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}
        },
        {
            "Concentrate",
            PhaseType::Concentrate,
            15.0f,
            3000.0f,
            {0.0f, 12.0f, 0.0f, 6.0f, 0.0f, 0.0f, 0.0f, 0.0f}
        },
        {
            "Wash",
            PhaseType::Wash,
            12.0f,
            2600.0f,
            {0.0f, 15.0f, 0.0f, 8.0f, 0.0f, 0.0f, 0.0f, 0.0f}
        },
        {
            "Harvest",
            PhaseType::Harvest,
            10.0f,
            800.0f,
            {0.0f, 0.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}
        }
    };
}

static std::vector<Particle> initLiveParticles(
    const AppConfig& config,
    const GeometryConfig& geometry
) {
    const int total = std::max(1, config.totalParticles);

    int cellParticles = std::max(1, total / 10);

    if (total == 1) {
        cellParticles = 1;
    }

    const int fluidParticles = total - cellParticles;

    std::vector<Particle> particles = initParticles(
        fluidParticles,
        cellParticles,
        geometry.chamberHeight,
        geometry.outerBase,
        geometry.outerTip,
        geometry.innerBase,
        geometry.innerTip
    );

    std::cout
        << "Particles: " << particles.size()
        << " total (" << fluidParticles << " fluid, "
        << cellParticles << " cells)\n";

    return particles;
}

static float computeChamberFlow(
    const std::vector<Line>& lines,
    const Step& step
) {
    float chamberFlow = 0.0f;

    for (const auto& line : lines) {
        if (!line.active) {
            continue;
        }

        if (line.sourceBag == CHAMBER_NODE ||
            line.targetBag == CHAMBER_NODE) {
            chamberFlow += step.flow_ml_min[static_cast<int>(line.id)];
        }
    }

    return chamberFlow;
}

// Advances one CPU simulation step: process-level system update followed by
// CPU particle update. Timing is accumulated separately for system and particle
// work so benchmarks can report where time is spent.
static void updateCpuFrame(
    std::vector<Particle>& particles,
    std::vector<Bag>& bags,
    std::vector<Line>& lines,
    Chamber& chamber,
    std::vector<Step>& protocol,
    int& currentStep,
    float& stepTimer,
    float dt,
    const GeometryConfig& geometry,
    BenchmarkStats& stats
) {
    Step& step = protocol[currentStep];

    const double systemStart = nowSeconds();

    updateSystem(bags, lines, chamber, step, dt);
    const float chamberFlow = computeChamberFlow(lines, step);

    const double systemEnd = nowSeconds();
    stats.systemUpdateMs += secondsToMs(systemEnd - systemStart);

    const double particleStart = nowSeconds();

    updateParticles(
        particles,
        dt,
        step.g_force,
        chamberFlow,
        geometry.chamberHeight,
        geometry.outerBase,
        geometry.outerTip,
        geometry.innerBase,
        geometry.innerTip
    );

    const double particleEnd = nowSeconds();
    stats.particleUpdateMs += secondsToMs(particleEnd - particleStart);

    stepTimer += dt;

    if (stepTimer >= step.duration_s) {
        std::cout
            << "Phase complete: " << step.name
            << " | retained=" << chamber.retained_cells
            << " | suspended=" << chamber.suspended_cells
            << " | omega=" << chamber.omega
            << std::endl;

        stepTimer = 0.0f;
        currentStep = (currentStep + 1) % static_cast<int>(protocol.size());
    }
}

#ifdef USE_CUDA

// Advances one CUDA simulation step. Process-level state is still updated on
// the CPU, while particle positions are updated by the CUDA backend.
// Timing includes live CUDA transfer, kernel execution, synchronization, and
// copy-back because the renderer consumes CPU-side particle data.
static bool updateCudaFrame(
    std::vector<Particle>& particles,
    std::vector<Bag>& bags,
    std::vector<Line>& lines,
    Chamber& chamber,
    std::vector<Step>& protocol,
    int& currentStep,
    float& stepTimer,
    float dt,
    const GeometryConfig& geometry,
    BenchmarkStats& stats
) {
    Step& step = protocol[currentStep];

    const double systemStart = nowSeconds();

    updateSystem(bags, lines, chamber, step, dt);
    const float chamberFlow = computeChamberFlow(lines, step);

    const double systemEnd = nowSeconds();
    stats.systemUpdateMs += secondsToMs(systemEnd - systemStart);

    const double particleStart = nowSeconds();

    const bool ok = updateParticlesCUDA(
        particles.data(),
        static_cast<int>(particles.size()),
        dt,
        step.g_force,
        chamberFlow,
        geometry.chamberHeight,
        geometry.outerBase,
        geometry.outerTip,
        geometry.innerBase,
        geometry.innerTip,
        phaseToInt(step.phase)
    );

    const double particleEnd = nowSeconds();
    stats.particleUpdateMs += secondsToMs(particleEnd - particleStart);

    if (!ok) {
        std::cerr << "CUDA particle update failed.\n";
        return false;
    }

    stepTimer += dt;

    if (stepTimer >= step.duration_s) {
        std::cout
            << "Phase complete: " << step.name
            << " | retained=" << chamber.retained_cells
            << " | suspended=" << chamber.suspended_cells
            << " | omega=" << chamber.omega
            << std::endl;

        stepTimer = 0.0f;
        currentStep = (currentStep + 1) % static_cast<int>(protocol.size());
    }

    return true;
}
#endif

static void updateReplayFrame(
    const ReplayData& replay,
    std::vector<Particle>& particles,
    int& replayFrame
) {
    if (replay.frameCount <= 0 || replay.particleCount <= 0 ||
        replay.frames.empty()) {
        return;
    }

    const int frameIndex = replayFrame % replay.frameCount;

    const std::size_t offset =
        static_cast<std::size_t>(frameIndex) *
        static_cast<std::size_t>(replay.particleCount);

    const std::size_t count =
        static_cast<std::size_t>(replay.particleCount);

    if (offset + count > replay.frames.size()) {
        std::cerr << "Replay frame offset out of range.\n";
        return;
    }

    particles.assign(
        replay.frames.begin() + static_cast<std::ptrdiff_t>(offset),
        replay.frames.begin() + static_cast<std::ptrdiff_t>(offset + count)
    );

    ++replayFrame;
}

static bool sanitizeParticlesForRender(
    std::vector<Particle>& particles,
    const GeometryConfig& geometry,
    const char* source
) {
    bool repairedAny = false;
    int repairedCount = 0;

    const float halfH = geometry.chamberHeight * 0.5f;
    const float maxR = std::max(geometry.outerBase, geometry.outerTip) * 1.05f;

    for (std::size_t i = 0; i < particles.size(); ++i) {
        Particle& p = particles[i];
        bool bad = false;

        if (!std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z) ||
            !std::isfinite(p.vx) || !std::isfinite(p.vy) || !std::isfinite(p.vz) ||
            !std::isfinite(p.diameter) || !std::isfinite(p.density)) {
            bad = true;
        }

        if (p.type != 0 && p.type != 1) {
            bad = true;
        }

        if (p.diameter <= 0.0f || p.diameter > 1.0f) {
            bad = true;
        }

        if (p.density <= 0.0f || p.density > 5.0f) {
            bad = true;
        }

        if (std::fabs(p.x) > maxR * 4.0f ||
            std::fabs(p.z) > maxR * 4.0f ||
            std::fabs(p.y) > geometry.chamberHeight * 4.0f) {
            bad = true;
        }

        if (bad) {
            if (repairedCount < 5) {
                std::cerr
                    << "[PARTICLE SANITIZER] " << source
                    << " repaired particle " << i
                    << " pos=(" << p.x << ", " << p.y << ", " << p.z << ")"
                    << " vel=(" << p.vx << ", " << p.vy << ", " << p.vz << ")"
                    << " type=" << p.type
                    << " diameter=" << p.diameter
                    << " density=" << p.density
                    << "\n";
            }

            p.x = 0.35f;
            p.y = -0.45f * geometry.chamberHeight;
            p.z = 0.0f;
            p.vx = 0.0f;
            p.vy = 0.0f;
            p.vz = 0.0f;
            p.type = 0;
            p.diameter = 0.06f;
            p.density = 1.0f;

            repairedAny = true;
            ++repairedCount;
        } else {
            p.y = std::max(-halfH, std::min(halfH, p.y));
            p.x = std::max(-maxR, std::min(maxR, p.x));
            p.z = std::max(-maxR, std::min(maxR, p.z));
            p.diameter = std::max(0.01f, std::min(0.25f, p.diameter));
        }
    }

    if (repairedCount > 0) {
        std::cerr << "[PARTICLE SANITIZER] repaired " << repairedCount
                  << " invalid particles from " << source
                  << " before rendering.\n";
    }

    return repairedAny;
}

// Renders one OpenGL frame: projection setup, chamber geometry, particles,
// buffer swap, and event polling. This work is intentionally excluded from
// headless benchmark mode.
static void renderFrame(
    GLFWwindow* window,
    const GeometryConfig& geometry,
    const std::vector<Particle>& particles
) {
    int fbWidth = 0;
    int fbHeight = 0;
    glfwGetFramebufferSize(window, &fbWidth, &fbHeight);

    glViewport(0, 0, fbWidth, fbHeight);
    glClearColor(0.05f, 0.05f, 0.08f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    setupProjection(fbWidth, fbHeight);

    glLoadIdentity();
    glTranslatef(0.0f, 0.0f, -5.0f);
    glRotatef(20.0f, 1.0f, 0.0f, 0.0f);
    glRotatef(
        static_cast<float>(glfwGetTime()) * 6.0f,
        0.0f,
        1.0f,
        0.0f
    );

    drawNestedConeChamber(
        geometry.outerBase,
        geometry.outerTip,
        geometry.innerBase,
        geometry.innerTip,
        geometry.chamberHeight
    );

    drawParticles(particles);

    glfwSwapBuffers(window);
    glfwPollEvents();
}

// Prints a common benchmark summary for visual, headless, and replay runs.
// The same summary format is parsed by the Python benchmark scripts.
static void printBenchmarkSummary(
    const BenchmarkStats& stats,
    std::size_t particleCount,
    RunMode mode,
    StepSelection stepSelection
) {
    const double totalSeconds = stats.totalRuntimeMs / 1000.0;
    const double safeSeconds = std::max(totalSeconds, 1e-9);
    const int safeFrames = std::max(stats.frames, 1);

    const double fps = static_cast<double>(stats.frames) / safeSeconds;
    const double avgFrameMs = stats.fullFrameMs / safeFrames;
    const double avgSystemMs = stats.systemUpdateMs / safeFrames;
    const double avgParticleMs = stats.particleUpdateMs / safeFrames;
    const double avgRenderMs = stats.renderMs / safeFrames;

    std::cout << std::fixed << std::setprecision(4);

    std::cout << "\n========== Benchmark Summary ==========\n";
    std::cout << "Mode: " << modeName(mode) << "\n";
    std::cout << "Step: " << stepName(stepSelection) << "\n";
    std::cout << "Particles: " << particleCount << "\n";
    std::cout << "Frames: " << stats.frames << "\n";
    std::cout << "Overall runtime: " << totalSeconds << " s\n";
    std::cout << "Average FPS: " << fps << "\n";
    std::cout << "Average full frame runtime: " << avgFrameMs << " ms/frame\n";
    std::cout << "Average system update runtime: " << avgSystemMs << " ms/frame\n";

    if (mode == RunMode::Cpu) {
        std::cout << "Average CPU particle update runtime: "
                  << avgParticleMs
                  << " ms/frame\n";

        std::cout << "Total CPU particle update runtime: "
                  << stats.particleUpdateMs / 1000.0
                  << " s\n";
    } else if (mode == RunMode::Cuda) {
        std::cout << "Average CUDA particle update runtime: "
                  << avgParticleMs
                  << " ms/frame\n";

        std::cout << "Total CUDA particle update runtime: "
                  << stats.particleUpdateMs / 1000.0
                  << " s\n";
    } else {
        std::cout << "Replay particle-frame copy runtime: "
                  << avgParticleMs
                  << " ms/frame\n";
        std::cout << "Replay note: particles were precomputed by the CUDA frame generator.\n";
    }

    std::cout << "Average render/swap/poll runtime: "
              << avgRenderMs
              << " ms/frame\n";

    std::cout << "=======================================\n";
}

// Runs the simulation update loop without creating an OpenGL window.
// This isolates CPU/CUDA update cost from rendering and display-loop overhead,
// making it the cleanest benchmark for particle-update performance.
static int runHeadlessBenchmark(const AppConfig& config) {
    GeometryConfig geometry;
    std::vector<Particle> particles = initLiveParticles(config, geometry);

    std::vector<Bag> bags;
    Chamber chamber{};
    std::vector<Line> lines;
    std::vector<Step> protocol;

    initCpuProtocol(
        bags,
        chamber,
        lines,
        protocol,
        config.stepSelection
    );

#ifdef USE_CUDA
    if (config.mode == RunMode::Cuda) {
        std::cerr << "[CUDA ENGINE] using persistent CUDA particle buffer\n";

        if (!initCudaParticleBuffer(static_cast<int>(particles.size()))) {
            std::cerr << "Failed to initialize CUDA particle buffer.\n";
            return 1;
        }
    }
#endif

    std::cout << "Mode: " << modeName(config.mode) << "\n";
    std::cout << "Step: " << stepName(config.stepSelection) << "\n";
    std::cout << "Headless: true\n";
    std::cout << "Update steps: " << config.benchmarkSteps << "\n";

    const float dt = 0.016f;
    int currentStep = 0;
    float stepTimer = 0.0f;

    BenchmarkStats stats;
    const double benchmarkStart = nowSeconds();

    for (int i = 0; i < config.benchmarkSteps; ++i) {
        const double frameStart = nowSeconds();

        if (config.mode == RunMode::Cpu) {
            updateCpuFrame(
                particles,
                bags,
                lines,
                chamber,
                protocol,
                currentStep,
                stepTimer,
                dt,
                geometry,
                stats
            );
        } else if (config.mode == RunMode::Cuda) {
#ifdef USE_CUDA
            if (!updateCudaFrame(
                    particles,
                    bags,
                    lines,
                    chamber,
                    protocol,
                    currentStep,
                    stepTimer,
                    dt,
                    geometry,
                    stats)) {
                shutdownCudaParticleBuffer();
                return 1;
            }
#else
            std::cerr
                << "CUDA mode requested, but this binary was built without CUDA support.\n";
            return 1;
#endif
        }

        const double frameEnd = nowSeconds();
        stats.fullFrameMs += secondsToMs(frameEnd - frameStart);
        stats.frames++;
    }

    const double benchmarkEnd = nowSeconds();
    stats.totalRuntimeMs = secondsToMs(benchmarkEnd - benchmarkStart);

    std::cout << "\n========== Headless Benchmark ==========\n";
    std::cout << "Mode: " << modeName(config.mode) << "\n";
    std::cout << "Step: " << stepName(config.stepSelection) << "\n";
    std::cout << "Particles: " << particles.size() << "\n";
    std::cout << "Update steps: " << config.benchmarkSteps << "\n";
    std::cout << "Simulated seconds: " << config.benchmarkSteps * dt << "\n";
    std::cout << "=======================================\n";

    printBenchmarkSummary(
        stats,
        particles.size(),
        config.mode,
        config.stepSelection
    );

#ifdef USE_CUDA
    if (config.mode == RunMode::Cuda) {
        shutdownCudaParticleBuffer();
    }
#endif

    return 0;
}

// Runs the interactive OpenGL application.
// This path measures end-to-end visual performance, including simulation update,
// CUDA transfer/synchronization when applicable, rendering, buffer swap, and
// event polling.
static int runApp(const AppConfig& config) {
    GeometryConfig geometry;
    ReplayData replay;
    std::vector<Particle> particles;

    if (config.mode == RunMode::Replay) {
        if (!loadReplayFile(config.replayPath, replay)) {
            return 1;
        }

        particles.resize(static_cast<std::size_t>(replay.particleCount));
    } else {
        particles = initLiveParticles(config, geometry);

#ifdef USE_CUDA
        if (config.mode == RunMode::Cuda) {
            std::cerr << "[CUDA ENGINE] using persistent CUDA particle buffer\n";
        }
#endif
    }

    GLFWwindow* window = createWindow(config);

    if (!window) {
        return 1;
    }

    std::cout << "Mode: " << modeName(config.mode) << "\n";
    std::cout << "Step: " << stepName(config.stepSelection) << "\n";

    if (config.durationSeconds > 0.0f) {
        std::cout << "Duration: " << config.durationSeconds << " seconds\n";
    } else {
        std::cout << "Duration: indefinite. Press ESC to exit.\n";
    }

    std::vector<Bag> bags;
    Chamber chamber{};
    std::vector<Line> lines;
    std::vector<Step> protocol;

    int currentStep = 0;
    float stepTimer = 0.0f;
    int replayFrame = 0;

    if (config.mode == RunMode::Cpu || config.mode == RunMode::Cuda) {
        initCpuProtocol(
            bags,
            chamber,
            lines,
            protocol,
            config.stepSelection
        );
    }

#ifdef USE_CUDA
    if (config.mode == RunMode::Cuda) {
        if (!initCudaParticleBuffer(static_cast<int>(particles.size()))) {
            std::cerr << "Failed to initialize CUDA particle buffer.\n";
            glfwDestroyWindow(window);
            glfwTerminate();
            return 1;
        }
    }
#endif

    const float cpuDt = 0.016f;
    float elapsedTime = 0.0f;

    BenchmarkStats stats;
    const double appStartTime = nowSeconds();

    while (!glfwWindowShouldClose(window)) {
        const double frameStart = nowSeconds();

        if (config.mode == RunMode::Cpu) {
            updateCpuFrame(
                particles,
                bags,
                lines,
                chamber,
                protocol,
                currentStep,
                stepTimer,
                cpuDt,
                geometry,
                stats
            );

            elapsedTime += cpuDt;
        } else if (config.mode == RunMode::Cuda) {
#ifdef USE_CUDA
            if (!updateCudaFrame(
                    particles,
                    bags,
                    lines,
                    chamber,
                    protocol,
                    currentStep,
                    stepTimer,
                    cpuDt,
                    geometry,
                    stats)) {
                glfwSetWindowShouldClose(window, GLFW_TRUE);
                break;
            }

            elapsedTime += cpuDt;
#else
            std::cerr
                << "CUDA mode requested, but this binary was built without CUDA support.\n";
            glfwSetWindowShouldClose(window, GLFW_TRUE);
#endif
        } else {
            const double replayStart = nowSeconds();

            updateReplayFrame(replay, particles, replayFrame);

            const double replayEnd = nowSeconds();
            stats.particleUpdateMs += secondsToMs(replayEnd - replayStart);

            elapsedTime += replay.dt;
        }

        if (config.mode == RunMode::Cpu) {
            sanitizeParticlesForRender(particles, geometry, "cpu");
        } else if (config.mode == RunMode::Cuda) {
            sanitizeParticlesForRender(particles, geometry, "cuda");
        } else {
            sanitizeParticlesForRender(particles, geometry, "replay");
        }

        if (config.durationSeconds > 0.0f &&
            elapsedTime >= config.durationSeconds) {
            std::cout
                << "Requested duration reached: "
                << config.durationSeconds
                << " seconds. Exiting.\n";

            glfwSetWindowShouldClose(window, GLFW_TRUE);
        }

        const double renderStart = nowSeconds();

        renderFrame(window, geometry, particles);

        const double renderEnd = nowSeconds();
        stats.renderMs += secondsToMs(renderEnd - renderStart);

        if (glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS) {
            glfwSetWindowShouldClose(window, GLFW_TRUE);
        }

        const double frameEnd = nowSeconds();
        stats.fullFrameMs += secondsToMs(frameEnd - frameStart);
        stats.frames++;
    }

    const double appEndTime = nowSeconds();
    stats.totalRuntimeMs = secondsToMs(appEndTime - appStartTime);

    printBenchmarkSummary(
        stats,
        particles.size(),
        config.mode,
        config.stepSelection
    );

#ifdef USE_CUDA
    if (config.mode == RunMode::Cuda) {
        shutdownCudaParticleBuffer();
    }
#endif

    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}

int main(int argc, char** argv) {
    AppConfig config;

    if (!parseArgs(argc, argv, config)) {
        return 1;
    }

    if (config.headless) {
        return runHeadlessBenchmark(config);
    }

    return runApp(config);
}